WebApplication7/Controllers/EksemplarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication7;

namespace WebApplication7
{
    partial class Eksemplar
    {
        string _Nimetus = "";
        string _Autor = "";
        public string Nimetus
        {
            get => RaamatNr == 0 ? _Nimetus : Raamat.Nimetus;
            set => _Nimetus = value;  
        }
        public string Autor
        {
            get => RaamatNr == 0 ? _Autor : Raamat.Autor;
            set => _Autor = value;
        }
    }
}

namespace WebApplication7.Controllers
{
    public class EksemplarController : Controller
    {
        private UusRaamatEntities db = new UusRaamatEntities();

        // GET: Eksemplar
        public ActionResult Index()
        {
            var eksemplar = db.Eksemplar.Include(e => e.Raamat);
            return View(eksemplar.ToList());
        }

        // GET: Eksemplar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eksemplar eksemplar = db.Eksemplar.Find(id);
            if (eksemplar == null)
            {
                return HttpNotFound();
            }
            return View(eksemplar);
        }

        // GET: Eksemplar/Create
        //public ActionResult Create()
        //{
        //    ViewBag.RaamatNr = new SelectList(db.Raamat, "Nr", "Nimetus");
        //    Eksemplar e = new Eksemplar();
        //    return View(e);
        //}

        // GET: Eksemplar/Create/id 
        public ActionResult Create(int? id)
        {
            ViewBag.Raamatud = db.Raamat.ToList();


            Raamat r = db.Raamat.Find(id??-1);
            Eksemplar e = new Eksemplar(); 
            if (r == null)
            {
                ViewBag.RaamatNr = new SelectList(db.Raamat, "Nr", "Nimetus");
            }
            else
            {
                e.RaamatNr = r.Nr;
                ViewBag.RaamatNr = new SelectList(db.Raamat, "Nr", "Nimetus", e.RaamatNr);

            }
            return View(e);
        }

        // POST: Eksemplar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nr,RaamatNr,Riiul,Nimetus,Autor")] Eksemplar eksemplar)
        {
            if (ModelState.IsValid)
            {
                db.Eksemplar.Add(eksemplar);

                if (eksemplar.RaamatNr == 0)
                {
                    Raamat u = db.Raamat.Where(x => x.Nimetus == eksemplar.Nimetus).Take(1).SingleOrDefault();
                    if (u == null)
                    {
                        db.Raamat.Add(u = new Raamat { Nimetus = eksemplar.Nimetus, Autor = eksemplar.Autor });
                        db.SaveChanges();
                    }
                    u.Eksemplar.Add(eksemplar);
                }
                db.SaveChanges();

                //return RedirectToAction("Detail","Raamat", new { id = eksemplar.RaamatNr });
                return RedirectToAction("Index", "Raamat");
            }

            ViewBag.RaamatNr = new SelectList(db.Raamat, "Nr", "Nimetus", eksemplar.RaamatNr);
            return View(eksemplar);
        }

        // GET: Eksemplar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eksemplar eksemplar = db.Eksemplar.Find(id);
            if (eksemplar == null)
            {
                return HttpNotFound();
            }
            ViewBag.RaamatNr = new SelectList(db.Raamat, "Nr", "Nimetus", eksemplar.RaamatNr);
            return View(eksemplar);
        }

        // POST: Eksemplar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Nr,RaamatNr,Riiul")] Eksemplar eksemplar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eksemplar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RaamatNr = new SelectList(db.Raamat, "Nr", "Nimetus", eksemplar.RaamatNr);
            return View(eksemplar);
        }

        // GET: Eksemplar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Eksemplar eksemplar = db.Eksemplar.Find(id);
            if (eksemplar == null)
            {
                return HttpNotFound();
            }
            return View(eksemplar);
        }

        // POST: Eksemplar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Eksemplar eksemplar = db.Eksemplar.Find(id);
            db.Eksemplar.Remove(eksemplar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication7/Controllers/RaamatController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication7;
using WebApplication7.Models;


namespace WebApplication7.Controllers
{
    public class RaamatController : Controller
    {
        private UusRaamatEntities db = new UusRaamatEntities();

        // GET: Raamats
        public ActionResult Index()
        {
            ViewBag.Ostukorv = Ostukorv.Korv;
            return View(db.Raamat.Where(x => x.Nr != 0).ToList());
        }

        public ActionResult Osta(int? id)
        {
            if (id.HasValue)
            {
                
                if (!Ostukorv.Korv.Keys.Contains(id.Value))
                    Ostukorv.Korv.Add(id.Value, new OstukorviRida { RaamatNr = id??0, Mitu = 0 });
                Ostukorv.Korv[id.Value].Mitu++;
            }
            return RedirectToAction("Index");
        }
        public ActionResult Maha(int? id)
        {
            if (id.HasValue)
            {
                if (Ostukorv.Korv.Keys.Contains(id.Value))
                {
                    Ostukorv.Korv[id.Value].Mitu--;
                    if (Ostukorv.Korv[id.Value].Mitu == 0) Ostukorv.Korv.Remove(id.Value);
                }


            }
            return RedirectToAction("Index");
        }

        // GET: Raamats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Raamat raamat = db.Raamat.Find(id);
            if (raamat == null)
            {
                return HttpNotFound();
            }
            return View(raamat);
        }

        // GET: Raamats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Raamats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nr,Nimetus,Autor")] Raamat raamat)
        {
            if (ModelState.IsValid)
            {
                db.Raamat.Add(raamat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(raamat);
        }

        // GET: Raamats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Raamat raamat = db.Raamat.Find(id);
            if (raamat == null)
            {
                return HttpNotFound();
            }
            return View(raamat);
        }

        // POST: Raamats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Nr,Nimetus,Autor,Hind")] Raamat raamat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(raamat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(raamat);
        }

        // GET: Raamats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Raamat raamat = db.Raamat.Find(id);
            if (raamat == null)
            {
                return HttpNotFound();
            }
            return View(raamat);
        }

        // POST: Raamats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Raamat raamat = db.Raamat.Find(id);
            db.Raamat.Remove(raamat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication7/Views/Raamat/Create.cshtml
@model WebApplication7.Raamat

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Raamat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nimetus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nimetus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nimetus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/Views/Raamat/Delete.cshtml
@model WebApplication7.Raamat

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Raamat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nimetus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nimetus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication7/Views/Raamat/Details.cshtml
@model WebApplication7.Raamat

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Raamat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nimetus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nimetus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <table>
            <tr>
                <th>Nr</th>
                <th>Riiul</th>
            </tr>
            @foreach(var eksemplar in Model.Eksemplar)
            {
                <tr>
                    <td>@eksemplar.Nr</td>
                    <td>@eksemplar.Riiul</td>
                </tr>
            }
        </table>
        
        @Html.ActionLink("Lisa eksemplar", $"Create/{Model.Nr}", "Eksemplar")


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Nr }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication7/Views/Raamat/Edit.cshtml
@model WebApplication7.Raamat

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Raamat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Nr)

        <div class="form-group">
            @Html.LabelFor(model => model.Nimetus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nimetus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nimetus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Hind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hind, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/Views/Raamat/Index.cshtml
@model IEnumerable<WebApplication7.Raamat>
@using WebApplication7.Models;
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nimetus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hind)
        </th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nimetus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hind)
        </td>
       <td>
            @Html.DisplayFor(modelItem => item.Eksemplar.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Nr }) |
            @Html.ActionLink("Details", "Details", new { id = item.Nr }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Nr }) |
            @Html.ActionLink("Osta", "Osta", new { id = item.Nr })
        </td>
    </tr>
}

    

</table>
<h2>Ostukorvis on</h2>
<table>
    @foreach (OstukorviRida or in ViewBag.Ostukorv.Values)
    {
        <tr>
            <td>
                @or.Raamat.Nimetus
            </td>
            <td>@or.Mitu</td>
            
            <td>|</td>
            <td>@Html.ActionLink("Eemalda", "Maha", new { id = or.RaamatNr })</td>
        </tr>
    }
    
</table>


@{

    IEnumerable<OstukorviRida> korv = ViewBag.Ostukorv.Values;
    var summa = korv.Select(x => x.Raamat.Hind * x.Mitu).Sum();
    <p>Ostukorvi summa: @summa</p>
}